#!/bin/bash
sed -i 's/swadeptcode=01\)/swadeptcode=30\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=16\)/swadeptcode=11\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=17\)/swadeptcode=6\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=18\)/swadeptcode=92\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=19\)/swadeptcode=23\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=19\)/swadeptcode=7\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=20\)/swadeptcode=28\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=20\)/swadeptcode=37\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=21\)/swadeptcode=22\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=21\)/swadeptcode=53\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=21\)/swadeptcode=82\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=23\)/swadeptcode=16\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=23\)/swadeptcode=7\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=24\)/swadeptcode=51\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=25\)/swadeptcode=6\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=26\)/swadeptcode=35\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=26\)/swadeptcode=49\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=3\)/swadeptcode=57\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=03\)/swadeptcode=67\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=30\)/swadeptcode=35\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=31\)/swadeptcode=26\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=31\)/swadeptcode=30\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=31\)/swadeptcode=37\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=31\)/swadeptcode=38\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=31\)/swadeptcode=48\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=31\)/swadeptcode=49\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=31\)/swadeptcode=99\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=35\)/swadeptcode=19\)/g' avio_pilot-filter-formated.txt
##sed -i 's/swadeptcode=35\)/swadeptcode=30\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=35\)/swadeptcode=30\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=35\)/swadeptcode=48\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=35\)/swadeptcode=56\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=37\)/swadeptcode=31\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=38\)/swadeptcode=30\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=40\)/swadeptcode=41\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=41\)/swadeptcode=24\)/g' avio_pilot-filter-formated.txt

sed -i 's/swadeptcode=44\)/swadeptcode=24\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=44\)/swadeptcode=67\)/g' avio_pilot-filter-formated.txt

sed -i 's/swadeptcode=46\)/swadeptcode=2\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=46\)/swadeptcode=2\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=46\)/swadeptcode=28\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=46\)/swadeptcode=28\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=49\)/swadeptcode=26\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=05\)/swadeptcode=58\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=51\)/swadeptcode=17\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=51\)/swadeptcode=25\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=51\)/swadeptcode=6\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=55\)/swadeptcode=0\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=55\)/swadeptcode=26\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=55\)/swadeptcode=41\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=55\)/swadeptcode=7\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=55\)/swadeptcode=98\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=56\)/swadeptcode=30\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=57\)/swadeptcode=3\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=06\)/swadeptcode=51\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=67\)/swadeptcode=82\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=71\)/swadeptcode=80\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=75\)/swadeptcode=30\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=08\)/swadeptcode=44\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=82\)/swadeptcode=0\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=82\)/swadeptcode=41\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=09\)/swadeptcode=98\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=93\)/swadeptcode=67\)/g' avio_pilot-filter-formated.txt
#sed -i 's/swadeptcode=93\)/swadeptcode=9\)/g' avio_pilot-filter-formated.txt
sed -i 's/swadeptcode=99\)/swadeptcode=48\)/g' avio_pilot-filter-formated.txt

