#main repos: 
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoPingOne.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoAuditBoard.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idtologicmonitor.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoVeracode.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idtoautocrib.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/AdminIDMgmt.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoFusion.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/RapidRewardsV2.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoACCESS.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoAD.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoAutoMessaging.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoAzureADDriver.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoBlog.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoCAFM.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoCargoPricing.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoCorpSecurity.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoCrowd.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoCSS.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoCustomer360.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoCyberArk.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoDocuWare.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoEDW.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoEmployeeCarePicture.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoEmployeeSvc.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoeTouches.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoFMS.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoGitLab.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoHubcast.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoIDF.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoiManage.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoKronos.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoLDAP.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoMaintenix.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoMC.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoOpsSuite.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoPoliteMail.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoProLaw.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoQualtrics.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSAPPhoto.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSirax.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSOAR.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSWAPAPhoto.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSWAUMobile.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoTCContacts.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoTCUsers.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoTririga.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoUSAN.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoVarolii.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoWiseleap.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/LDAPtoID.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/LMS.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/MCL.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/NotificationLoopback.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/OpenOptionsPhotoID.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/OQS.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/AccessLoopBack.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/ACCESStoID.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/BadgetoID.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/BeelineContractors.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/BusinessLogic.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/Comply365.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/DirXMLDriverSet.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/DriverSetV3.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/EmployeeServicesRoleMgmtDriver.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/EntitlementServiceDriver-DS1.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/EntitlementServiceDriver-DSv3.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/HRLifeView.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/RACF.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/RoleAndResourceDriver.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/RoleManagementDriver.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/SAPHRBusinessLogic.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/SAPHRLoopback.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/SAPHRUser.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/SAPHRWorkOrder.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/SDCDriverSet.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/ServiceNow.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/Trax.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/UserApplicationDriver.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/WorkdayDataMaint.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/zApproved.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/SAPHR.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/BeelineSupplData.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/WorkdayBusinessLogic.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/WorkdayHCM.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoTRIM.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSumTotal.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/testrevision.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/temporarynewdrivertest.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSAPGRC.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idtoperkspot.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSAPSolman.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idm-demo.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/driverset-dirxml.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/driverset-aev1.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/driverset-aev2.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/driverset-v3.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/driverset-sdc.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idtoalvaria.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/global-idm-library.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/IDtoSAPFiori.git
#IDMUnit: 
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-idm-unit-extend.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/idm-unit-dtf-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/idm-unit-crowd-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/idm-unit-ntlm-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/idm-unit-sap-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/idmunit-dependencies.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-idm-unit.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-rest-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-jms-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-ldap-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-ntlm-soap-client-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-sap-client-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-sap-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-soap-client-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swau-mobile-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/css-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/mcl-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/oqs-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-scim-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/swa-xsl-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/dirxml-ldap-connector.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/idmunit/cyberark-connector.git
#common: 
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-vpc-deployment-sailpoint.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-iam-roles-deploy.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-common-kms-module.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/eDirectory-PowerShell-Tools.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/Git-Training.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/iam-data-integrity.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/IDMUnit.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/IDMUnitLib.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/docker-idmunit.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/ant-idmunit-tests.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/docker-ant.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/pipeline-fragments.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/micro-focus-postman-collection.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/idmunit-utils.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/docker-dir-tools.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/idm-groups-data-cleansing.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/test-project.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/smtp-cert-checker.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/deployment-configuration.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/install-cert.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/swa-diff-viewer.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/igajavatools.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/docker-java8-build.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/idm-rds-aurora-postgres-db.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-vpc-deployment.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/allocate-cidr.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-deploy-aurora-cluster.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-deploy-pgadmin.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-pg-deploy-private-cert.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/csiga-deploy-db-schema.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/AlteaReconTool.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/WD.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/netiq-deployer.git
git clone git@southwest.gitlab-dedicated.com:csiam/idm/common/app-as-id-data-files.git
#myaccess: 
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/gitlab-dedicated.git
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/workday-user-based-collection.git
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/workday-role-based-collection.git
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/myaccess-postman-collection.git
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/dash-pid-node.git
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/pam-group-creation-node.git
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/swa-custom-nodes.git
git clone git@southwest.gitlab-dedicated.com:csiam/myaccess/merge-script.git
