git clone ssh://git@git.trivir.com:7999/swa/idtoperkspot.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/micro-focus-postman-collection.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSAPGRC.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/sap-solman.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/temporarynewdrivertest.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/testrevision.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSumTotal.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoTRIM.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/WorkdayHCM.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/WorkdayBusinessLogic.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/BeelineSupplData.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/SAPHR.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/zApproved.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/WorkdayDataMaint.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/UserApplicationDriver.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/Trax.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/ServiceNow.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/SDCDriverSet.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/SAPHRWorkOrder.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/SAPHRUser.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/SAPHRLoopback.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/SAPHRBusinessLogic.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/RoleManagementDriver.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/RoleAndResourceDriver.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/RACF.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/PWNotification.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/PhoneDir.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/HRLifeView.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/FO_eFileScanner.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/EntitlementServiceDriver-DSv3.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/EntitlementServiceDriver-DS1.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/EmployeeServicesRoleMgmtDriver.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/eFileScanner.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/DriverSetV3.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/DirXMLDriverSet.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/Comply365.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/BusinessLogic.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/BeelineContractors.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/BadgetoID.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/Altea.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/ACCESStoID.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/AccessLoopBack.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/OQS.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/OpenOptionsPhotoID.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/NotificationLoopback.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/MCL.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/LMS.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/LDAPtoID.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoWiseleap.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoVarolii.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoUSAN.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoTririga.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoTCUsers.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoTCContacts.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSWAUMobile.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSWAPAPhoto.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSOAR.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSirax.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSecDB.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoSAPPhoto.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoQualtrics.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoProLaw.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoPoliteMail.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoOpsSuite.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoMC.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoMaintenix.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoLMS.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoLDAP.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoKronos.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoiManage.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoIDF.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoHubcast.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoGitLabGroup.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoGitLab.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoFMS.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoeTouches.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoEmployeeSvc.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoEmployeeCarePicture.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoEDW.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoDocuWare.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoCyberArk.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoCustomer360.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoCSS.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoCrowd.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoCorpSecurity.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoCargoPricing.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoCAFM.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoBlog.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoAzureADDriver.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoAutoMessaging.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoAD.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoACCESS.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/RapidRewardsV2.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/aarons-deleteable-test-project.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/IDtoFusion.git 2>> errors.txt
git clone ssh://git@git.trivir.com:7999/swa/AdminIDMgmt.git 2>> errors.txt
